services:

  adoptly-user:
    build:
      dockerfile: ./Dockerfile
    container_name: adoptly-user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:17
    container_name: postgresql
    environment:
      POSTGRES_USER: root_user
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: adoptly_user_db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root_user", "-d", "adoptly_user_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data: